import blockchain from './assets/blockchain.jpg'
import cyber from './assets/cyber.jpg'
import business from './assets/image2.jpg'
import dash from './assets/image1.jpg'
import full from './assets/full.jpg'
import forex from './assets/forex.png'
import shake from './assets/AI-Shake.png'
import project from './assets/project.jpg'

export const coursesData = [
    {
      id: 1,
      image: full,
      name: 'FullStack development with React & NodeJS',
      price: '130',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Learn full stack development with React and NodeJS, covering everything from the basics to advanced topics.',
        language: 'Language - English [Subtitle Added]',
        date: 'Posted on June 15, 2024'
      },
      phase1: {
        phaseName: 'React JS Basic Concept',
        phaseList: 'Introduction',
        phaseList1: 'JSX Introduction',
        phaseList2: 'Components',
        phaseList3: 'Conditional rendering',
        phaseList4: 'Props Drilling',
      },
      phase2: {
        phaseName: 'Hooks Introduction',
        phaseList: 'useState Hooks',
        phaseList1: 'useEffect Hooks',
        phaseList2: 'useRef Hooks',
        phaseList3: 'useMemo Hooks',
        phaseList4: 'useContext Hook',
      },
      phase3: {
        phaseName: 'Introduction to React Redux',
        phaseList: 'Context API',
        phaseList1: 'React Events introduction',
        phaseList2: 'onclick capture events',
        phaseList3: 'onsubmit capture events',
        phaseList4: 'onscroll events',
      },
      phase4: {
        phaseName: 'Lifecycle of components',
        phaseList: 'Introduction to constructors',
        phaseList1: 'component DidMount',
        phaseList2: 'componentWillUnmount',
        phaseList3: 'componentDidUpdate',
        phaseList4: 'componentDidCatch',
      }
    },
    {
      id: 2,
      image: business,
      name: 'Python For Data Analysis',
      price: '110',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Master Python for data analysis, including libraries such as Pandas, NumPy, and Matplotlib.',
        language: 'English (US)',
         date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Introduction to Data Analysis',
        phaseList: 'Introduction to Python',
        phaseList1: 'Setting up the environment',
        phaseList2: 'Basic Python syntax',
        phaseList3: 'Data types and variables',
        phaseList4: 'Control flow and functions',
      },
      phase2: {
        phaseName: 'Pandas and DataFrames',
        phaseList: 'Introduction to Pandas',
        phaseList1: 'Series and DataFrames',
        phaseList2: 'DataFrame operations',
        phaseList3: 'Reading and writing data',
        phaseList4: 'Data manipulation and cleaning',
      },
      phase3: {
        phaseName: 'Data Visualization with Matplotlib',
        phaseList: 'Introduction to Matplotlib',
        phaseList1: 'Creating basic plots',
        phaseList2: 'Customizing plots',
        phaseList3: 'Subplots and layouts',
        phaseList4: 'Advanced plotting techniques',
      },
      phase4: {
        phaseName: 'Advanced Data Analysis',
        phaseList: 'Advanced Pandas operations',
        phaseList1: 'Time series analysis',
        phaseList2: 'Machine learning with Python',
        phaseList3: 'Data analysis projects',
        phaseList4: 'Final project and assessment',
      }
    },
    {
      id: 3,
      image: dash,
      name: 'Business Analysis',
      price: '160',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Comprehensive course on business analysis, covering all essential concepts and techniques.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Introduction to Business Analysis',
        phaseList: 'What is Business Analysis?',
        phaseList1: 'Role of a Business Analyst',
        phaseList2: 'Key Skills and Competencies',
        phaseList3: 'BA Techniques',
        phaseList4: 'Stakeholder Analysis',
      },
      phase2: {
        phaseName: 'Requirements Gathering',
        phaseList: 'Requirements Elicitation',
        phaseList1: 'Requirements Documentation',
        phaseList2: 'Requirements Validation',
        phaseList3: 'Use Case Modelling',
        phaseList4: 'Requirements Management',
      },
      phase3: {
        phaseName: 'Business Process Modeling',
        phaseList: 'Introduction to BPMN',
        phaseList1: 'Creating BPMN Diagrams',
        phaseList2: 'Business Process Improvement',
        phaseList3: 'Value Stream Mapping',
        phaseList4: 'Process Reengineering',
      },
      phase4: {
        phaseName: 'Solution Assessment & Validation',
        phaseList: 'Defining Solution Scope',
        phaseList1: 'Solution Evaluation Techniques',
        phaseList2: 'Risk Management',
        phaseList3: 'Performance Metrics',
        phaseList4: 'Final Assessment and Case Study',
      }
    },
    {
      id: 4,
      image: forex,
      name: 'Ultimate Forex Trading Course',
      price: '90',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Learn the fundamentals of Forex trading, including strategies and risk management.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024'
      },
      phase1: {
        phaseName: 'Introduction to Forex Trading',
        phaseList: 'Forex Market Overview',
        phaseList1: 'Basic Forex Terminology',
        phaseList2: 'Types of Forex Pairs',
        phaseList3: 'Forex Brokers',
        phaseList4: 'Trading Platforms',
      },
      phase2: {
        phaseName: 'Technical Analysis',
        phaseList: 'Charts and Patterns',
        phaseList1: 'Indicators and Oscillators',
        phaseList2: 'Trend Analysis',
        phaseList3: 'Support and Resistance',
        phaseList4: 'Trading Strategies',
      },
      phase3: {
        phaseName: 'Fundamental Analysis',
        phaseList: 'Economic Indicators',
        phaseList1: 'News Trading',
        phaseList2: 'Market Sentiment',
        phaseList3: 'Global Events Impact',
        phaseList4: 'Fundamental Strategies',
      },
      phase4: {
        phaseName: 'Risk Management',
        phaseList: 'Risk to Reward Ratio',
        phaseList1: 'Position Sizing',
        phaseList2: 'Stop Loss Techniques',
        phaseList3: 'Money Management',
        phaseList4: 'Psychological Aspects of Trading',
      }
    },
    {
      id: 5,
      image: shake,
      name: 'Introduction To Artificial Intelligence',
      price: '150',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Explore the fundamentals of Artificial Intelligence, including machine learning and neural networks.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Introduction to AI',
        phaseList: 'What is AI?',
        phaseList1: 'History of AI',
        phaseList2: 'AI vs Machine Learning',
        phaseList3: 'Applications of AI',
        phaseList4: 'Future of AI',
      },
      phase2: {
        phaseName: 'Machine Learning Basics',
        phaseList: 'Supervised Learning',
        phaseList1: 'Unsupervised Learning',
        phaseList2: 'Reinforcement Learning',
        phaseList3: 'Common Algorithms',
        phaseList4: 'Data Preparation',
      },
      phase3: {
        phaseName: 'Neural Networks',
        phaseList: 'Introduction to Neural Networks',
        phaseList1: 'Perceptron and Multilayer Perceptron',
        phaseList2: 'Backpropagation',
        phaseList3: 'Convolutional Neural Networks',
        phaseList4: 'Recurrent Neural Networks',
      },
      phase4: {
        phaseName: 'AI Project',
        phaseList: 'Defining the Project',
        phaseList1: 'Data Collection and Preparation',
        phaseList2: 'Model Selection and Training',
        phaseList3: 'Model Evaluation',
        phaseList4: 'Deployment and Maintenance',
      }
    },
    {
      id: 6,
      image: project,
      category: 'popular',
      name: 'Project Management Course',
      price: '125',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'A complete guide to project management, covering all phases from initiation to closing.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Project Initiation',
        phaseList: 'Project Lifecycle',
        phaseList1: 'Initiating Projects',
        phaseList2: 'Project Charter',
        phaseList3: 'Stakeholder Identification',
        phaseList4: 'Setting Objectives',
      },
      phase2: {
        phaseName: 'Project Planning',
        phaseList: 'Scope Management',
        phaseList1: 'Time Management',
        phaseList2: 'Cost Management',
        phaseList3: 'Quality Management',
        phaseList4: 'Risk Management',
      },
      phase3: {
        phaseName: 'Project Execution',
        phaseList: 'Executing the Plan',
        phaseList1: 'Team Management',
        phaseList2: 'Communication Management',
        phaseList3: 'Procurement Management',
        phaseList4: 'Change Management',
      },
      phase4: {
        phaseName: 'Project Closure',
        phaseList: 'Closing Processes',
        phaseList1: 'Final Deliverables',
        phaseList2: 'Lessons Learned',
        phaseList3: 'Project Evaluation',
        phaseList4: 'Celebrating Success',
      }
    },
    {
      id: 7,
      image: cyber,
      category: 'popular',
      name: 'ISC2 Cyber Security',
      price: '110',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Comprehensive cyber security training covering all aspects from basics to advanced topics.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Introduction to Cyber Security',
        phaseList: 'Cyber Security Fundamentals',
        phaseList1: 'Types of Attacks',
        phaseList2: 'Security Policies',
        phaseList3: 'Risk Management',
        phaseList4: 'Ethical Hacking',
      },
      phase2: {
        phaseName: 'Network Security',
        phaseList: 'Network Protocols',
        phaseList1: 'Firewalls and VPNs',
        phaseList2: 'Intrusion Detection Systems',
        phaseList3: 'Wireless Security',
        phaseList4: 'Cryptography',
      },
      phase3: {
        phaseName: 'Application Security',
        phaseList: 'Secure Software Development',
        phaseList1: 'Web Application Security',
        phaseList2: 'Mobile Security',
        phaseList3: 'Secure Coding Practices',
        phaseList4: 'Application Testing',
      },
      phase4: {
        phaseName: 'Security Management',
        phaseList: 'Security Audits',
        phaseList1: 'Incident Response',
        phaseList2: 'Disaster Recovery',
        phaseList3: 'Compliance and Regulations',
        phaseList4: 'Security Policies and Procedures',
      }
    },
    {
      id: 8,
      image: blockchain,
      category: 'popular',
      name: 'BlockChain and Cryptocurrency',
      price: '200',
      standard: 'Beginners to Advanced',
      courseDetail :{
        description: 'Learn about blockchain technology and cryptocurrencies, including their applications and future potential.',
        language: 'English (US)',
        date: 'Posted on June 15, 2024',
      },
      phase1: {
        phaseName: 'Introduction to Blockchain',
        phaseList: 'What is Blockchain?',
        phaseList1: 'How Blockchain Works',
        phaseList2: 'Blockchain Features',
        phaseList3: 'Blockchain vs Traditional Databases',
        phaseList4: 'Applications of Blockchain',
      },
      phase2: {
        phaseName: 'Cryptocurrency Basics',
        phaseList: 'Introduction to Cryptocurrencies',
        phaseList1: 'Bitcoin and Altcoins',
        phaseList2: 'Cryptocurrency Mining',
        phaseList3: 'Wallets and Exchanges',
        phaseList4: 'Investing in Cryptocurrencies',
      },
      phase3: {
        phaseName: 'Smart Contracts',
        phaseList: 'What are Smart Contracts?',
        phaseList1: 'How Smart Contracts Work',
        phaseList2: 'Ethereum and Smart Contracts',
        phaseList3: 'Use Cases of Smart Contracts',
        phaseList4: 'Challenges and Risks',
      },
      phase4: {
        phaseName: 'Future of Blockchain and Cryptocurrency',
        phaseList: 'Emerging Trends',
        phaseList1: 'Blockchain in Various Industries',
        phaseList2: 'Regulatory Challenges',
        phaseList3: 'Security and Privacy Issues',
        phaseList4: 'Future Predictions',
      }
    },
]
